jasypt: 
  encryptor: 
    password: e!Jd&ljyJ^e4I5oU
server: 
     port: 8073
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=true
    username: ENC(BjTeKYrhGjTixlMjuacy8Q==)
    password: ENC(BjTeKYrhGjTixlMjuacy8Q==)
mybatis: 
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.cts.spring.boot.demo.bean 